general:
  collectTelemetryData: false
  verbose: true
steps:
  gctsDeploy:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'WRGCTS21_2'
    repository: 'bav-22-wrgcts21_2'
  gctsExecuteABAPUnitTests:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'WRGCTS21_2'
    repository: 'bav-22-wrgcts21_2'
  gctsRollback:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'WRGCTS21_2'
    repository: 'bav-22-wrgcts21_2'
  abapEnvironmentRunATCCheck:
    host: 'gprd.sapds.ru:44300'
    atcConfig: 'atcconfig.yml'
    abapCredentialsId: 'WRGCTS21_2'
    dockerPullImage: false
  
